### ISSUE TITLE
inconsistent terminology in the New Environment page

### ISSUE THREAD

**Issue by martinpovolny** [aeolusproject/conductor#149]
at /pool_families/new I see section title: "New Environment"

but below a label for a text field reads: "Pool Family Name"

**Comment by razorinc** [comment]
And you can't send a patch for it?

**Comment by aathomas** [comment]
This is a tricky one. 

Pool Families is definitely wrong, and we need to rename the controllers etc..

However, there are problems with "Environment" too (See the recent thread on the developer list about reconciling names)

So, it isn't clear what the correct name should be. It will become clear soon, though, and, once we have a new name, it should be applied consistently, thoughout the code, the APIs, and the UI.

**Comment by jcoufal** [comment]
I think that @razorinc wanted to point out, that sometimes it's faster to fix issue right away, than filling tickets.

Regarding renaming all components, it's more tricky as @aathomas mentioned.

But right now in the UI there are "Environments" everywhere so it is obvious that Pool Family should be changed. Until we get into real renaming (will take some time), this quick fix in the UI would be useful.

**Comment by aathomas** [comment]
@jcoufal is correct. For the time being, the correct name to use consistently in the UI is "Environments"

**Comment by martinpovolny** [comment]
@jcoufal: yes, sometimes it's faster, sometimes not

for me atm, it's not

I am trying to post issues that I come across while doing other work and even reporting the issue breaks me from the thing I work on

but enough of this

**Comment by razorinc** [comment]
@jcoufal That's exactly what I meant.
@martinpovolny Yeah, I understand but delegating does not actually always work, I think would be better if you can write a quick patch and see how it's going.
