### ISSUE TITLE
Login validation message right after start

### ISSUE THREAD

**Issue by jcoufal** [aeolusproject/conductor#164]
When I start Conductor I get "success" validation message, that I need to be logged first to enter the system. For the very first time, the message shouldn't be there, it is obvious, that I need to log in to enter (messages are valid to display just after error login, sending password, etc.). Or is there any other reason to display it right away? For me, it feels more confusing.

**Comment by jtomasek** [comment]
I'll have a look at this, It should appear only when you try to access the page that requires the user to be logged in. At least I'll fix it to be a warning in my notifications patch.

**Comment by jtomasek** [comment]
Implemented in https://github.com/aeolusproject/conductor/pull/167
