### ISSUE TITLE
Implement List deployables

### ISSUE THREAD

**Issue by hacxman** [aeolusproject/conductor#168]
parent issue - https://redmine.aeolusproject.org/redmine/issues/3929
RM href - https://redmine.aeolusproject.org/redmine/issues/3930

**Comment by tzumainn** [comment]
When listing deployables, can we ensure that there's an option to list deployables by pool?  In other words, find all catalogs associated with a pool, and return all the deployables in those catalogs.

**Comment by hacxman** [comment]
code was pushed. closing
