### ISSUE TITLE
pool_families_provider_accounts records not deleted when deleting provider_accounts

### ISSUE THREAD

**Issue by martinpovolny** [aeolusproject/conductor#346]
(and vice versa most likely)

the use of has_and_belongs_to_many is generally discouraged as it does not support :dependent=> :destroy which would be sort of obvious required behavior here

so we have to:

1) replace HABTM in app/models/pool_family.rb with has_many

2) check other HABTM through conductor

this is a blocker for adding the foreign keys

**Comment by sseago** [comment]
On 01/17/2013 04:36 AM, Martin Povolny wrote:

> the use of has_and_belongs_to_many is generally discouraged as it does 
> not support :dependent=> :destroy which would be sort of obvious 
> required behavior here
> 
> so we have to:
> 
> 1) replace HABTM in app/models/pool_family.rb with has_many
> 
> 2) check other HABTM through conductor
> 
> this is a blocker for adding the foreign keys
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/aeolusproject/conductor/issues/346.
> 
> So this isn't a simple swap with has_many, but instead you need a 
> has_many :through with an intermediate model that belongs_to both 
> PoolFamily and ProviderAccount. This is because not only does a pool 
> family have multiple provider accounts, but a provider account can be 
> attached to multiple pool families.

Scott

**Comment by martinpovolny** [comment]
sure, that is clear, it's a simple swap with has_many :through ;-)

**Comment by martinpovolny** [comment]
I have fixed this issue by adding before_destroy hooks on both sides of the M:N relation

seems cleaner to me then adding a whole new model just to get the referential integrity right 

see #339
