### ISSUE TITLE
Cucumber tests run twice

### ISSUE THREAD

**Issue by jzigmund** [aeolusproject/conductor#398]
When you run cuke test (all features, a feature, scenario), it will run twice. Can be checked also in travis-ci.

**Comment by martinpovolny** [comment]
fixed in TIM by https://github.com/aeolus-incubator/tim/issues/107

**Comment by martinpovolny** [comment]
as a quick fix before having new TIM, you can delete your equivalent of _/home/martin/.gem/ruby/1.9.1/gems/tim-0.2.0/lib/tasks/cucumber.rake_
